### ISSUE TITLE
Change branch from "master" to "main"

### ISSUE THREAD

**Issue by kersten1** [riscv-non-isa/riscv-asm-manual#102]
As a gentle reminder, the "Friendly Terminology" policy [link](https://docs.google.com/document/d/1lmEMU_Gi1KRQB2PtbjUSgbtlx5frUK40AuMO1OICSEY/) which uses the "Inclusive Naming" community [link](https://inclusivenaming.org/) includes the word "master" as a [Tier 1: Replace Immediately](https://inclusivenaming.org/word-lists/tier-1/) word.

You can follow these steps to rename your branch: https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab

**Comment by cmuellner** [comment]
Renamed `master` branch to `main` using the GitHub UI, which also took care of the following:
* update 7 pull requests targeting this branch across 7 repositories.
* update 1 branch protection that explicitly targets

Closing as completed.

CC: @kito-cheng
