### ISSUE TITLE
Missing pseudo-instructions?

### ISSUE THREAD

**Issue by AFOliveira** [riscv-non-isa/riscv-asm-manual#110]
I've been digging for pseudoinstructions in [binutils ](https://github.com/bminor/binutils-gdb/blob/master/opcodes/riscv-opc.c )and found that several pseudoinstructions implemented there are not found in the ASM Manual, is this on purpose?

For reference, these are some, but not all of those pseudo-instructions:

bs.v
vfneg.v
vmclr.m
vmfge.vv 
vmfgt.vv 
vmmv.m 
vmnot.m 
vmset.m
vmsge.vi
vmsge.vv
vmsge.vx
vmsgeu.vi
vmsgeu.vv
vmsgeu.vx
vmsgt.vv
vmsgtu.vv 
vmslt.vi
vmsltu.vi
vneg.v
vnot.v
vt.maskc
vt.maskcn
vwcvt.x.x.v
vwcvtu.x.x.v

**Comment by cmuellner** [comment]
Good catch! All of them (assuming that the first one in your list (`bs.v`) is `vfabs.v`) are specified as pseudoinstructions (incl. what they translate to) in the ratified vector extension specification. Therefore, they are clearly specified, but were not added here.

Would you be interested in creating a PR that adds them?

**Comment by AFOliveira** [comment]
Definitely so! I will work on that and tag this issue. Thank you!
