### ISSUE TITLE
Is there a CI job or are there releases of this document?

### ISSUE THREAD

**Issue by axel-h** [riscv-non-isa/riscv-asm-manual#112]
It seem there is no CI job that builds the document and there are also no releases of this document. So I wonder, where this is published actually? Shouldn't this be at https://lf-riscv.atlassian.net/wiki/spaces/HOME/pages/16154769/RISC-V+Technical+Specifications then?

The link behind "`jira.riscv.org/browse/RVG-4`" in the project descriptio is also broken, it tries to open https://jira.riscv.org/browse/RVG-4, but this seems to be https://lf-riscv.atlassian.net/browse/RVG-4 now?

**Comment by apazos** [comment]
Hi @axel-h,
There is no CI jobs, but it is a good suggestion and we will work on it!

This Asm Manual, along with the Toolchain Conventions and C-API documents are non-ISA specifications under development.
You can find them at https://github.com/riscv-non-isa. 
The link you posted refers to non-ISA specifications that have been published.

Thanks for pointing out, the Jira link seems to be indeed broken. Will fix it!

**Comment by axel-h** [comment]
Hi @apazos,

To get things started, in https://github.com/axel-h/riscv-asm-manual/tree/patch-axel-20241123 I have added a workflow based on that the other RISC-V workflows do. It can build a PDF, but I'm still trying to figure out the release part.

**Comment by wmat** [comment]
I went ahead and merged @axel-h PR for the CI.  You may want to look at the workflows used on the riscv-isa-manual repository and tweak what's here accordingly.  Similarly, if you'd prefer that I do this, let me know.

**Comment by axel-h** [comment]
Thanks. So we have the first official document build here now, see https://github.com/riscv-non-isa/riscv-asm-manual/actions/runs/12198852957

**Comment by apazos** [comment]
Hi @axel-h, thanks for pushing the CI workflow.
I was going to use the CI workflow from the RVI docs template available at 
https://github.com/riscv/docs-spec-template/blob/main/.github/workflows/build-pdf.yml
Thanks @wmat for merging.
