### ISSUE TITLE
Setup instructions 

### ISSUE THREAD

**Issue by katieworton** [riscv-non-isa/riscv-asm-manual#14]
It would be useful to have a section explaining how to run the code, possibly in the form of a "Getting Started" subsection.

**Comment by axel-h** [comment]
While this would be nice, I don't think this is really part of the assembly manual. This manual can't explain "the word", and should stay focused on the specific topic it covers. How to run things should be part of a manual that comes with your toolchain, simulator or board. For e.g. GCC, LLVM, and QEMU there is extensive documentation already. Bot there is always room for improvement there for the RISC-V part.

**Comment by cmuellner** [comment]
Closing this outdated issue, which is not directly related to this repo.
