### ISSUE TITLE
RISC-V simulator

### ISSUE THREAD

**Issue by quantrpeter** [riscv-non-isa/riscv-asm-manual#49]
Hi
   We are trsting our RISC-V simulator, is there any very big assembly example code ?
thanks
Peter

**Comment by axel-h** [comment]
You can have a look at:
- https://github.com/riscv-non-isa/riscv-arch-test
- https://github.com/riscv-software-src/riscv-tests
- https://github.com/riscv-software-src/riscof
- https://github.com/anycore/anycore-riscv-tests
- https://github.com/riscv-ovpsim/imperas-riscv-tests
- https://www.embench.org

**Comment by cmuellner** [comment]
Closing this outdated issue which is not directly related to this repo.

**Comment by quantrpeter** [comment]
[like]  Peter Cheung reacted to your message:
________________________________
