### ISSUE TITLE
Code size reduction specification (`C`, `Zca`, `Zcd`, `Zcf` and other `Zc*` extensions)

### ISSUE THREAD

**Issue by a4lg** [riscv-non-isa/riscv-asm-manual#91]
[Recently ratified code size reduction specification](https://github.com/riscv/riscv-code-size-reduction/releases/tag/v1.0.4-1) possibly causes a few problems on this manual and toolchains.

This is because `C` should be expanded following the conventional rule (where "contain" and "imply" are equivalent, just like that `M` *implies* `Zmmul` while `Zmmul` is *a subset of* `M`).

| Before          | After Expansion                                |
|-----------------|------------------------------------------------|
| `C`             | `C` + `Zca`                                    |
| `C` + `F`       | `C` + `Zca` + `Zcf`         + `F` (RV32)       |
| `C` + `F`       | `C` + `Zca`                 + `F` (RV64)       |
| `C` + `F` + `D` | `C` + `Zca` + `Zcf` + `Zcd` + `F` + `D` (RV32) |
| `C` + `F` + `D` | `C` + `Zca`         + `Zcd` + `F` + `D` (RV64) |

[My branch on GNU Binutils](https://github.com/a4lg/binutils-gdb/wiki/riscv_ext_imply_complex) implemented this expansion rule.

Should we stop implying `Zca` etc. from `C`?
Should we make any countermeasures or special rules?

I would like to hear your thoughts.

## 1. Example on `arch`

```
.option arch, -c # Disable compressed extension, we can't use any instruction in extension.
memcpy_norvc:
```

It will stop working since `-c` *will not* disable `C` extension subsets including relevant `Zca`, as warned on a NOTE on the `.option arch` description.

It seems no code on GitHub truly depends on `.option arch, -c` (except Binutils testcases).

### 2.1. `.option norvc` equivalents

```
.option push
.option arch, -c   # Alternative of .option norvc
.option pop
```

It will not be true either.  The most robust solution is to use only `+c` unless we don't want any compressed instructions.

### 2.2. What should `.option norvc` disable?

In the `.option rvc/norvc` section,

> Enable/disable the C-extension for the following code region.

It does not mention any `C` extension subsets.
IMO, it's natural to disable all `C` extension subsets: `Zca`, `Zcd` and `Zcf` by `.option norvc` (on my GNU Binutils branch, I implemented to do so, but not other compressed extensions like `Zcb`).

What do you think?

**Comment by pz9115** [comment]
> [Recently ratified code size reduction specification](https://github.com/riscv/riscv-code-size-reduction/releases/tag/v1.0.4-1) possibly causes a few problems on this manual and toolchains.
> 
> This is because `C` should be expanded following the conventional rule (where "contain" and "imply" are equivalent, just like `M` _implies_ `Zmmul` while `Zmmul` is _a subset of_ `M`).

IMO, C and ZC are two separate extensions，C will never imply any ZC extension at all. They just have some common instructions, and ZC need supports the same features of compressed instructions as C(like alignment). 

> 
> Before	After Expansion
> `C`	`C` + `Zca`
> `C` + `F`	`C` + `Zca` + `Zcf` + `F` (RV32)
> `C` + `F`	`C` + `Zca` + `F` (RV64)
> `C` + `F` + `D`	`C` + `Zca` + `Zcf` + `Zcd` + `F` + `D` (RV32)
> `C` + `F` + `D`	`C` + `Zca` + `Zcd` + `F` + `D` (RV64)

You can think of Zca/f/d as a subset of C, so there will be:

`C`                          `C`
`C` + `Zca`              `C`
`C` + `Zcf`               `C` + `F`
`C` + `Zcd`              `C` + `F` + `D` (D will imply F)

> [My branch on GNU Binutils](https://github.com/a4lg/binutils-gdb/wiki/riscv_ext_imply_complex) implemented this expansion rule.
> 
> Should we stop implying `Zca` etc. from `C`? Should we make any countermeasures or special rules?
> 
> I would like to hear your thoughts.
> 
> ## 1. Example on `arch`
> ```
> .option arch, -c # Disable compressed extension, we can't use any instruction in extension.
> memcpy_norvc:
> ```
> 
> It will stop working since `-c` _will not_ disable `C` extension subsets including relevant `Zca`, as warned on a NOTE on the `.option arch` description.
> 
> It seems no code on GitHub truly depends on `.option arch, -c` (except Binutils testcases).
> 
> ## 2. `.option norvc`
> ### 2.1. `.option norvc` equivalents
> ```
> .option push
> .option arch, -c   # Alternative of .option norvc
> .option pop
> ```
> 
> It will not be true either. The most robust solution is to use only `+c` unless we don't want any compressed instructions.
> 
> ### 2.2. What should `.option norvc` disable?
> In the `.option rvc/norvc` section,
> 
> > Enable/disable the C-extension for the following code region.
> 
> It does not mention any `C` extension subsets. IMO, it's natural to disable all `C` extension subsets: `Zca`, `Zcd` and `Zcf` by `.option norvc` (on my GNU Binutils branch, I implemented to do so, but not other compressed extensions like `Zcb`).
> 
> What do you think?

**Comment by a4lg** [comment]
> IMO, C and ZC are two separate extensions，

That would have been convincing if `Zmmul` was *not* implied by `M` (but it *is* implied).
Note that `M` doesn't mention that it depends on `Zmmul`.

I checked the QEMU implementation and found that it expands the `C` extension (to `Zca`, `Zcf` and `Zcd` on the privileged specification 1.12 or later.  That's not self-explanatory but possibly a workaround for older architectures.

## The Past

1. Clear conclusion is made: "depend" and "imply" are equivalent (if `A` depends on `B`, `A` will imply `B`).
2. Many follow but no clear conclusions: "contain" and "imply" are equivalent.

`Zmmul` and `M` is the prime example. As I explained earlier, `Zmmul` is an implied extension from `M` despite the fact that `M` does not state that it depends on `Zmmul` (although `Zmmul` is defined to be a `M` subset).

There's a different example.  We haven't incorporated implied extensions like `Zkr` → `Zicsr` into GNU Binutils.  `Zkr` is an *unprivileged* extension with a new CSR but because it wasn't clear whether `Zicsr` should be implied or not (at the time, I added implications from *privileged* extensions to `Zicsr` because the privileged architecture itself depends on the `Zicsr` extension).

## My Opinion

IMO, this case is much like `M` and `Zmmul`.

Because this change is more breaking than that, we should monitor the situation well and possibly make compatibility measures for possible problems that may arise.  However, I don't agree that `Zca` is *not* an implied extension from `C`.

If we need an integer compressed instruction, checking `Zca` should be sufficient, not `C || Zca`.

**Comment by a4lg** [comment]
## An Absurd Idea for RVC Compatibility

Cancel deprecation of `.option rvc` and `.option norvc` and redefine their roles.

As of this writing, I feel this idea is nothing more than a joke.  But depending on the following discussion, it may get a bit realistic.

**Comment by pz9115** [comment]
> If we need a base compressed integer instruction, checking `Zca` should be sufficient, not `C || Zca`.

It's a way to enable the compress feature, maybe we need change `C` extension description in isa-spec.

**Comment by a4lg** [comment]
Hmm, in either case, I would like to hear thoughts from many.

**Comment by aswaterman** [comment]
We can clarify the ISA specs in this regard if need be.  What do you think the most pragmatic way to deal with M vs. Zmmul is?  (I assume that having M imply Zmmul makes it easiest for programmers, so that if they want to check if the `mul` instruction is present, they simply check `__riscv_zmmul`, rather than having to check for the union of two things.)

**Comment by nick-knight** [comment]
I support resolving this in the ISA spec. Here is my PR: https://github.com/riscv/riscv-isa-manual/pull/1121 . I don't have appropriate permissions to request reviewers.

**Comment by a4lg** [comment]
@cmuellner @aswaterman
I see.  That is the second best option for me (as a toolchain developer; if I wasn't, that would have been the best).  Being faithful to the specification is itself consistent and makes sense.

@cmuellner
Yes, that subtraction would be a problem.  Depending on what `Zcmop` will depend, a new headache may appear and I think less subtraction (`.option arch, -SOMETHING`) is better.

@nick-knight
Thanks for the proposal!  I don't want to look at two separate things for existence of multiplication instructions and at least I want to keep `M` → `Zmmul`.  If we need to be faithful to the specification, modifying the specification to imply `Zmmul` from `M` is the best thing we can do.

I'll close this issue in a couple of days.

**Comment by kito-cheng** [comment]
Some idea here is we may introduce `.option nocompressed`, `.option nofloat` and `.option .novector` to disable compressed extension, floating point extension and vector extension.

This also may resolve an issue around `.option arch, -c`, `.option arch, -f` and `.option arch, -v`, those operation are kind of unclear before due to the implication rules`*`, however introduce new set of `.option no*` should resolve that.

`*` some example here:
- -march=rv64gcv with `.option -v` will result `rv64gc_zv64d` instead of `rv64gcv`, which is not expected and counter-intuitive result.
- -march=rv64gc` with `.option -f` will result `rv64gc` like NOP because `d` will make `f` back because implication.

**Comment by cmuellner** [comment]
> Some idea here is we may introduce `.option nocompressed`, `.option nofloat` and `.option .novector` to disable compressed extension, floating point extension and vector extension.

Do we have a use-case for `nofloat` and `novector` for the assembler? I only see use cases for compilers. As ASM programmer you know which instructions you are using. And the mapping from ASM to opcodes is unambiguous for float and vector instructions.

The option `nocompressed`/`-c`/`norvc` is special, because a some ASM instructions can be encoded in two ways (4-byte encoding and compressed encoding). In this case the programmer cannot make assumptions about the instruction size, which is a problem in some cases. Here, disabling compressed instructions makes the assembler's behavior predictable (4-byte per instruction). That's the only use-case for extension-subtraction that I am aware of.

I would avoid extension-subtraction unless we have a use case that we cannot solve in another way.

**Comment by fanghuaqi** [comment]
Hello genius,

I want to ask about how to disable any compressed instruction generation in asm language, as I can see in https://github.com/riscv-non-isa/riscv-asm-manual/blob/3b06fa93fd52f277e8e0dc180bbb2ceec1ff5957/src/asm-manual.adoc?plain=1#L323-L325

~~~asm
.option push     # Push current option to the stack.
.option arch, -c # Disable compressed extension, we can't use any instruction in extension.
memcpy_norvc:
~~~

Can I use this `.option arch, -c` to disable any compressed instruction generation, such as `zca`, `zcb`, `zcf`, `zcd`, `zcmp`, `zcmt` and `zclsd` and some future maybe introduced compressed instruction, if it is not possible, it seems it will be hard to write a general asm code to just disable any compressed instruction without any compiler generated macros?

And there are many imply rules(zcf -> zca) and mutual exclusion rules(eg. zcd vs zcmp) for compressed extension, so it will really hard for a freshman to write an easy asm code to just disable any compressed instruction generation.

Thanks

**Comment by a4lg** [comment]
@fanghuaqi
Writing without `+x` or `-x` will help (you can write full ISA string in `.option arch` and all you need to care is to (1) match base ISA like RV32E or RV64I and (2) no extensions with compressed instructions are enabled).

```
# Example:
.option arch, rv64i
```

**Comment by fanghuaqi** [comment]
> @fanghuaqi Writing without `+x` or `-x` will help (you can write full ISA string in `.option arch` and all you need to care is to (1) match base ISA like RV32E or RV64I and (2) no extensions with compressed instructions are enabled).
> 
> ```
> # Example:
> .option arch, rv64i
> ```

Thanks, but for my case, this arch may vary in many different arch combination, but want to disable compression instruction. This kind method will not work for me.

**Comment by a4lg** [comment]
@fanghuaqi
I understand that some will vary but...

*   You can use macros (or external preprocessors) and...
*   It's hard for me to imagine the situation where you need to write *much of* assembly (and *partially* without compressed instructions) so that the solution above is not applicable.

For instance, my example above restricts available instructions to plain RV64I *inside that `.option push...pop` region* but you can mix other objects with different extensions (but with the same ISA).  If you *really* need to use `.option arch` with "*anything* minus compressed instructions", you are likely doing things over-complicated.

**Comment by fanghuaqi** [comment]
Hi @a4lg , thank you for your suggestion. I will think it deeper to see whether there are better solution.
