### ISSUE TITLE
enhancement request: please could a pdf version, or pdf frindlier version be created?

### ISSUE THREAD

**Issue by peepo** [riscv-non-isa/riscv-asm-manual#96]
Hi there,

just beginning to look into risc-v implementation on fpga, so please be kind/patient.

I tried using firefox to print #riscv-asm.md however on my uptodate firefox 122.0  

printing the table: Registers of the RV32I. Based on RISC-V documentation and Patterson and Waterman "The RISC-V Reader" (2017)

28 blank pages are inserted between

x8 	s0 or fp 	saved register 0 or frame pointer 	yes

and

x9 	s1 	saved register 1 	yes

quite likely a firefox bug, but....

anyway thanks for considering.

**Comment by cmuellner** [comment]
Thanks for bringing this up. I fully agree with that request.

We were thinking about converting this repo (and others) to AsciiDoc, to bring them in line with all other RISC-V documents (e.g. https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc).
However, we did not assign this task a high enough priority to get this done.

**Comment by peepo** [comment]
filed at Mozilla as bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1878606
