### ISSUE TITLE
Two suggested improvements to the pseudo instruction table

### ISSUE THREAD

**Issue by secworks** [riscv-non-isa/riscv-asm-manual#98]
I would like to suggest two improvements to the table with pseudo instructions:

1. For pseudo instructions that maps to more than one real instruction, put the real instructions on separate lines. Today the real instructions are separated with ';', and the second instruction is wrapped half way onto the next line. This makes it quite hard to see the real instructions and their operands, fields.

2. Somewhere, either before or after the table explain 'myriad sequences', an expression which only appears in the table. For non-native English speakers, this short expression may be hard to understand what it implies.

**Comment by cmuellner** [comment]
Both suggestions sound good.
Are you interested in providing PRs as well?

**Comment by cmuellner** [comment]
Fixed with #101.

**Comment by secworks** [comment]
Looks really good!
